### ISSUE TITLE
Cannot identify image file

### ISSUE THREAD

**Issue by Dizro** [FluffyMaguro/Streetview-panorama-scraping#2]
When running the 2_download_panoramas.py file, the program throws: "cannot identify image file %r" % (filename if filename is still fp) PIL.UnidentifiedImageError: Unable to identify image file 'tiles/WAacpY6bBjTsCv5XvV1a_Q_0x0.jpg'

Can this be fixed somehow?

**Comment by FluffyMaguro** [comment]
I added a fix
